name: pytest
on: [push]

jobs:
  pytest:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11' ]
        os: [ ubuntu, windows, macos ]
      fail-fast: false

    name: ${{ matrix.python-version }} ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.3
      - name: run Pytest
        run: |
          poetry install
          poetry run nox -s pytest
