name: pytest
on: [ push, pull_request ]

jobs:
  pytest:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]
        os: [ ubuntu ]
      fail-fast: false

    name: ${{ matrix.python-version }} ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: BSFishy/pip-action@v1
      with:
        packages: nox
    - run: nox -s pytest
